### ISSUE TITLE
Deprecation of node16

### ISSUE THREAD

**Issue by huelsmc** [LasaleFamine/action-ff-merge#1]
Hi,
could you provide a new version based on node20 (16 has been [deprecated](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/)).

Thanks in advance!

**Comment by LasaleFamine** [comment]
Thanks for the issue.

I did release a v2 version with node20 via https://github.com/LasaleFamine/action-ff-merge/commit/f9705334da1c38dd21e370cc7703cb030df83588
